// Voxel Block Registry - Theo's Generate (70+ Authentic Blocks)

export const BLOCK_TYPES = {
  AIR: 0,
  GRASS: 1,
  DIRT: 2,
  STONE: 3,
  COBBLESTONE: 4,
  OAK_WOOD: 5,
  OAK_LEAVES: 6,
  GLASS: 7,
  SAND: 8,
  WATER: 9,
  BRICKS: 10,
  ROOF_TILE: 11,
  GOLD_BLOCK: 12,
  DIAMOND_BLOCK: 13,
  GLOWSTONE: 14,
  OBSIDIAN: 15,
  MARBLE: 16,
  IRON_BLOCK: 17,
  BOOKSHELF: 18,
  SNOW: 19,

  // --- 50+ NEW EXPANDED BLOCKS ---
  // Woods & Planks
  OAK_PLANKS: 20,
  BIRCH_WOOD: 21,
  BIRCH_PLANKS: 22,
  SPRUCE_WOOD: 23,
  SPRUCE_PLANKS: 24,
  JUNGLE_WOOD: 25,
  JUNGLE_PLANKS: 26,
  ACACIA_WOOD: 27,
  ACACIA_PLANKS: 28,
  DARK_OAK_WOOD: 29,
  DARK_OAK_PLANKS: 30,
  CHERRY_WOOD: 31,
  CHERRY_LEAVES: 32,
  CHERRY_PLANKS: 33,

  // Ores
  COAL_ORE: 34,
  IRON_ORE: 35,
  COPPER_ORE: 36,
  GOLD_ORE: 37,
  REDSTONE_ORE: 38,
  LAPIS_ORE: 39,
  EMERALD_ORE: 40,
  DIAMOND_ORE: 41,
  NETHER_QUARTZ_ORE: 42,

  // Natural & Geological Stones
  GRANITE: 43,
  POLISHED_GRANITE: 44,
  DIORITE: 45,
  POLISHED_DIORITE: 46,
  ANDESITE: 47,
  POLISHED_ANDESITE: 48,
  DEEPSLATE: 49,
  COBBLED_DEEPSLATE: 50,
  BASALT: 51,
  BLACKSTONE: 52,
  NETHERRACK: 53,
  SOUL_SAND: 54,
  END_STONE: 55,
  PRISMARINE: 56,
  DARK_PRISMARINE: 57,
  SEA_LANTERN: 58,
  AMETHYST_BLOCK: 59,

  // Utility, Crafting & Interactive
  CRAFTING_TABLE: 60,
  FURNACE: 61,
  CHEST: 62,
  TNT: 63,
  SPONGE: 64,
  SLIME_BLOCK: 65,
  HONEYCOMB_BLOCK: 66,
  HAY_BALE: 67,

  // Nature, Plants & Food
  PUMPKIN: 68,
  JACK_O_LANTERN: 69,
  MELON: 70,
  CACTUS: 71,
  RED_MUSHROOM_BLOCK: 72,

  // Vibrant Colored Wool / Concrete Blocks
  WOOL_WHITE: 73,
  WOOL_RED: 74,
  WOOL_BLUE: 75,
  WOOL_GREEN: 76,
  WOOL_YELLOW: 77,
  WOOL_BLACK: 78,
  WOOL_ORANGE: 79,
  WOOL_PURPLE: 80,
  WOOL_CYAN: 81,
  WOOL_PINK: 82,

  // --- CLASSIC STUDIO & STUDDED BLOCKS ---
  BASEPLATE: 83,
  SPAWN_PLATE: 84,
  NEON_CYAN: 85,
  NEON_ORANGE: 86,
  NEON_PINK: 87,
  STUD_BRICK_RED: 88,
  STUD_BRICK_BLUE: 89,
  STUD_BRICK_YELLOW: 90,

  // --- 16+ AUTHENTIC FURNITURE BLOCKS ---
  SOFA_RED: 91,
  SOFA_BLUE: 92,
  WOOD_TABLE: 93,
  CHAIR_WOOD: 94,
  BED_RED: 95,
  BED_BLUE: 96,
  LAMP_TABLE: 97,
  TELEVISION: 98,
  KITCHEN_FRIDGE: 99,
  KITCHEN_STOVE: 100,
  KITCHEN_SINK: 101,
  TOILET: 102,
  BATH_TUB: 103,
  WALL_CLOCK: 104,
  HOUSE_PLANT: 105,
  OFFICE_COMPUTER: 106
};

export const BLOCK_DEFS = {
  [BLOCK_TYPES.AIR]: { id: 0, name: 'Air', solid: false, transparent: true, color: '#000000' },
  [BLOCK_TYPES.GRASS]: { id: 1, name: 'Grass Block', solid: true, transparent: false, color: '#4c9e22', sound: 'grass', hardness: 0.6, faces: { top: 'grass_top', side: 'grass_side', bottom: 'dirt' } },
  [BLOCK_TYPES.DIRT]: { id: 2, name: 'Dirt', solid: true, transparent: false, color: '#866043', sound: 'dirt', hardness: 0.5, faces: { all: 'dirt' } },
  [BLOCK_TYPES.STONE]: { id: 3, name: 'Smooth Stone', solid: true, transparent: false, color: '#7a7a7a', sound: 'stone', hardness: 1.5, faces: { all: 'stone' } },
  [BLOCK_TYPES.COBBLESTONE]: { id: 4, name: 'Cobblestone', solid: true, transparent: false, color: '#636363', sound: 'stone', hardness: 1.8, faces: { all: 'cobblestone' } },
  [BLOCK_TYPES.OAK_WOOD]: { id: 5, name: 'Oak Log', solid: true, transparent: false, color: '#685332', sound: 'wood', hardness: 1.2, faces: { top: 'wood_top', side: 'wood_side', bottom: 'wood_top' } },
  [BLOCK_TYPES.OAK_LEAVES]: { id: 6, name: 'Oak Leaves', solid: true, transparent: true, color: '#3a7d20', sound: 'grass', hardness: 0.3, faces: { all: 'leaves' } },
  [BLOCK_TYPES.GLASS]: { id: 7, name: 'Glass', solid: true, transparent: true, opacity: 0.4, color: '#cce6ff', sound: 'glass', hardness: 0.3, faces: { all: 'glass' } },
  [BLOCK_TYPES.SAND]: { id: 8, name: 'Sand', solid: true, transparent: false, color: '#d9c68c', sound: 'sand', hardness: 0.5, faces: { all: 'sand' } },
  [BLOCK_TYPES.WATER]: { id: 9, name: 'Water', solid: false, transparent: true, fluid: true, opacity: 0.7, color: '#1c6bd9', sound: 'water', faces: { all: 'water' } },
  [BLOCK_TYPES.BRICKS]: { id: 10, name: 'Red Bricks', solid: true, transparent: false, color: '#9c4538', sound: 'stone', hardness: 2.0, faces: { all: 'bricks' } },
  [BLOCK_TYPES.ROOF_TILE]: { id: 11, name: 'Roof Tiles', solid: true, transparent: false, color: '#b3412a', sound: 'stone', hardness: 1.6, faces: { all: 'roof_tile' } },
  [BLOCK_TYPES.GOLD_BLOCK]: { id: 12, name: 'Gold Block', solid: true, transparent: false, color: '#f5c62b', sound: 'stone', hardness: 2.5, faces: { all: 'gold' } },
  [BLOCK_TYPES.DIAMOND_BLOCK]: { id: 13, name: 'Diamond Block', solid: true, transparent: false, color: '#63dede', sound: 'stone', hardness: 3.0, faces: { all: 'diamond' } },
  [BLOCK_TYPES.GLOWSTONE]: { id: 14, name: 'Glowstone Lantern', solid: true, transparent: false, emissive: '#ffdd6b', color: '#ffda5c', sound: 'glass', hardness: 0.4, faces: { all: 'glowstone' } },
  [BLOCK_TYPES.OBSIDIAN]: { id: 15, name: 'Obsidian', solid: true, transparent: false, color: '#181026', sound: 'stone', hardness: 4.0, faces: { all: 'obsidian' } },
  [BLOCK_TYPES.MARBLE]: { id: 16, name: 'Polished Marble', solid: true, transparent: false, color: '#f5f7fa', sound: 'stone', hardness: 1.5, faces: { all: 'marble' } },
  [BLOCK_TYPES.IRON_BLOCK]: { id: 17, name: 'Iron Block', solid: true, transparent: false, color: '#d9dce0', sound: 'stone', hardness: 2.2, faces: { all: 'iron' } },
  [BLOCK_TYPES.BOOKSHELF]: { id: 18, name: 'Bookshelf', solid: true, transparent: false, color: '#866043', sound: 'wood', hardness: 1.0, faces: { top: 'wood_top', side: 'bookshelf', bottom: 'wood_top' } },
  [BLOCK_TYPES.SNOW]: { id: 19, name: 'Snow Block', solid: true, transparent: false, color: '#f0f5fc', sound: 'grass', hardness: 0.4, faces: { all: 'snow' } },

  // Woods & Planks
  [BLOCK_TYPES.OAK_PLANKS]: { id: 20, name: 'Oak Planks', solid: true, transparent: false, color: '#a88953', sound: 'wood', hardness: 1.0, faces: { all: 'oak_planks' } },
  [BLOCK_TYPES.BIRCH_WOOD]: { id: 21, name: 'Birch Log', solid: true, transparent: false, color: '#d5d4ce', sound: 'wood', hardness: 1.2, faces: { top: 'wood_top', side: 'birch_wood', bottom: 'wood_top' } },
  [BLOCK_TYPES.BIRCH_PLANKS]: { id: 22, name: 'Birch Planks', solid: true, transparent: false, color: '#c7b483', sound: 'wood', hardness: 1.0, faces: { all: 'birch_planks' } },
  [BLOCK_TYPES.SPRUCE_WOOD]: { id: 23, name: 'Spruce Log', solid: true, transparent: false, color: '#3d2b18', sound: 'wood', hardness: 1.2, faces: { top: 'wood_top', side: 'spruce_wood', bottom: 'wood_top' } },
  [BLOCK_TYPES.SPRUCE_PLANKS]: { id: 24, name: 'Spruce Planks', solid: true, transparent: false, color: '#684d2a', sound: 'wood', hardness: 1.0, faces: { all: 'spruce_planks' } },
  [BLOCK_TYPES.JUNGLE_WOOD]: { id: 25, name: 'Jungle Log', solid: true, transparent: false, color: '#574519', sound: 'wood', hardness: 1.2, faces: { top: 'wood_top', side: 'jungle_wood', bottom: 'wood_top' } },
  [BLOCK_TYPES.JUNGLE_PLANKS]: { id: 26, name: 'Jungle Planks', solid: true, transparent: false, color: '#9e724f', sound: 'wood', hardness: 1.0, faces: { all: 'jungle_planks' } },
  [BLOCK_TYPES.ACACIA_WOOD]: { id: 27, name: 'Acacia Log', solid: true, transparent: false, color: '#676157', sound: 'wood', hardness: 1.2, faces: { top: 'wood_top', side: 'acacia_wood', bottom: 'wood_top' } },
  [BLOCK_TYPES.ACACIA_PLANKS]: { id: 28, name: 'Acacia Planks', solid: true, transparent: false, color: '#ba6337', sound: 'wood', hardness: 1.0, faces: { all: 'acacia_planks' } },
  [BLOCK_TYPES.DARK_OAK_WOOD]: { id: 29, name: 'Dark Oak Log', solid: true, transparent: false, color: '#322312', sound: 'wood', hardness: 1.2, faces: { top: 'wood_top', side: 'dark_oak_wood', bottom: 'wood_top' } },
  [BLOCK_TYPES.DARK_OAK_PLANKS]: { id: 30, name: 'Dark Oak Planks', solid: true, transparent: false, color: '#422a14', sound: 'wood', hardness: 1.0, faces: { all: 'dark_oak_planks' } },
  [BLOCK_TYPES.CHERRY_WOOD]: { id: 31, name: 'Cherry Log', solid: true, transparent: false, color: '#4a2530', sound: 'wood', hardness: 1.2, faces: { top: 'wood_top', side: 'cherry_wood', bottom: 'wood_top' } },
  [BLOCK_TYPES.CHERRY_LEAVES]: { id: 32, name: 'Cherry Leaves', solid: true, transparent: true, color: '#f79ac0', sound: 'grass', hardness: 0.3, faces: { all: 'cherry_leaves' } },
  [BLOCK_TYPES.CHERRY_PLANKS]: { id: 33, name: 'Cherry Planks', solid: true, transparent: false, color: '#e098a5', sound: 'wood', hardness: 1.0, faces: { all: 'cherry_planks' } },

  // Ores
  [BLOCK_TYPES.COAL_ORE]: { id: 34, name: 'Coal Ore', solid: true, transparent: false, color: '#2b2b2b', sound: 'stone', hardness: 2.0, faces: { all: 'coal_ore' } },
  [BLOCK_TYPES.IRON_ORE]: { id: 35, name: 'Iron Ore', solid: true, transparent: false, color: '#c9a589', sound: 'stone', hardness: 2.2, faces: { all: 'iron_ore' } },
  [BLOCK_TYPES.COPPER_ORE]: { id: 36, name: 'Copper Ore', solid: true, transparent: false, color: '#cb6e4f', sound: 'stone', hardness: 2.0, faces: { all: 'copper_ore' } },
  [BLOCK_TYPES.GOLD_ORE]: { id: 37, name: 'Gold Ore', solid: true, transparent: false, color: '#f0c742', sound: 'stone', hardness: 2.5, faces: { all: 'gold_ore' } },
  [BLOCK_TYPES.REDSTONE_ORE]: { id: 38, name: 'Redstone Ore', solid: true, transparent: false, emissive: '#ee2222', color: '#d81e1e', sound: 'stone', hardness: 2.2, faces: { all: 'redstone_ore' } },
  [BLOCK_TYPES.LAPIS_ORE]: { id: 39, name: 'Lapis Lazuli Ore', solid: true, transparent: false, color: '#184d9f', sound: 'stone', hardness: 2.2, faces: { all: 'lapis_ore' } },
  [BLOCK_TYPES.EMERALD_ORE]: { id: 40, name: 'Emerald Ore', solid: true, transparent: false, color: '#17b045', sound: 'stone', hardness: 2.8, faces: { all: 'emerald_ore' } },
  [BLOCK_TYPES.DIAMOND_ORE]: { id: 41, name: 'Diamond Ore', solid: true, transparent: false, color: '#4ee2d6', sound: 'stone', hardness: 3.0, faces: { all: 'diamond_ore' } },
  [BLOCK_TYPES.NETHER_QUARTZ_ORE]: { id: 42, name: 'Nether Quartz Ore', solid: true, transparent: false, color: '#eae4d9', sound: 'stone', hardness: 1.8, faces: { all: 'quartz_ore' } },

  // Natural & Geological Stones
  [BLOCK_TYPES.GRANITE]: { id: 43, name: 'Granite', solid: true, transparent: false, color: '#9a6a58', sound: 'stone', hardness: 1.6, faces: { all: 'granite' } },
  [BLOCK_TYPES.POLISHED_GRANITE]: { id: 44, name: 'Polished Granite', solid: true, transparent: false, color: '#9e6d5b', sound: 'stone', hardness: 1.6, faces: { all: 'polished_granite' } },
  [BLOCK_TYPES.DIORITE]: { id: 45, name: 'Diorite', solid: true, transparent: false, color: '#c4c4c5', sound: 'stone', hardness: 1.6, faces: { all: 'diorite' } },
  [BLOCK_TYPES.POLISHED_DIORITE]: { id: 46, name: 'Polished Diorite', solid: true, transparent: false, color: '#d5d5d6', sound: 'stone', hardness: 1.6, faces: { all: 'polished_diorite' } },
  [BLOCK_TYPES.ANDESITE]: { id: 47, name: 'Andesite', solid: true, transparent: false, color: '#888889', sound: 'stone', hardness: 1.6, faces: { all: 'andesite' } },
  [BLOCK_TYPES.POLISHED_ANDESITE]: { id: 48, name: 'Polished Andesite', solid: true, transparent: false, color: '#8a8a8b', sound: 'stone', hardness: 1.6, faces: { all: 'polished_andisite' } },
  [BLOCK_TYPES.DEEPSLATE]: { id: 49, name: 'Deepslate', solid: true, transparent: false, color: '#4d4d53', sound: 'stone', hardness: 2.2, faces: { all: 'deepslate' } },
  [BLOCK_TYPES.COBBLED_DEEPSLATE]: { id: 50, name: 'Cobbled Deepslate', solid: true, transparent: false, color: '#3f3f45', sound: 'stone', hardness: 2.4, faces: { all: 'cobbled_deepslate' } },
  [BLOCK_TYPES.BASALT]: { id: 51, name: 'Basalt', solid: true, transparent: false, color: '#4a4b4e', sound: 'stone', hardness: 1.8, faces: { all: 'basalt' } },
  [BLOCK_TYPES.BLACKSTONE]: { id: 52, name: 'Blackstone', solid: true, transparent: false, color: '#2a242a', sound: 'stone', hardness: 2.0, faces: { all: 'blackstone' } },
  [BLOCK_TYPES.NETHERRACK]: { id: 53, name: 'Netherrack', solid: true, transparent: false, color: '#682525', sound: 'stone', hardness: 0.6, faces: { all: 'netherrack' } },
  [BLOCK_TYPES.SOUL_SAND]: { id: 54, name: 'Soul Sand', solid: true, transparent: false, color: '#4d3b31', sound: 'sand', hardness: 0.5, faces: { all: 'soul_sand' } },
  [BLOCK_TYPES.END_STONE]: { id: 55, name: 'End Stone', solid: true, transparent: false, color: '#e0dfa7', sound: 'stone', hardness: 2.5, faces: { all: 'end_stone' } },
  [BLOCK_TYPES.PRISMARINE]: { id: 56, name: 'Prismarine', solid: true, transparent: false, color: '#5f9d94', sound: 'stone', hardness: 1.8, faces: { all: 'prismarine' } },
  [BLOCK_TYPES.DARK_PRISMARINE]: { id: 57, name: 'Dark Prismarine', solid: true, transparent: false, color: '#2e4f48', sound: 'stone', hardness: 1.8, faces: { all: 'dark_prismarine' } },
  [BLOCK_TYPES.SEA_LANTERN]: { id: 58, name: 'Sea Lantern', solid: true, transparent: false, emissive: '#b4e8e1', color: '#b4e8e1', sound: 'glass', hardness: 0.4, faces: { all: 'sea_lantern' } },
  [BLOCK_TYPES.AMETHYST_BLOCK]: { id: 59, name: 'Amethyst Block', solid: true, transparent: false, color: '#885ca6', sound: 'glass', hardness: 1.5, faces: { all: 'amethyst' } },

  // Utility, Crafting & Interactive
  [BLOCK_TYPES.CRAFTING_TABLE]: { id: 60, name: 'Crafting Table', solid: true, transparent: false, color: '#7a5a3a', sound: 'wood', hardness: 1.5, faces: { top: 'crafting_top', side: 'crafting_side', bottom: 'oak_planks' } },
  [BLOCK_TYPES.FURNACE]: { id: 61, name: 'Furnace', solid: true, transparent: false, color: '#666666', sound: 'stone', hardness: 2.0, faces: { top: 'stone', side: 'furnace_side', bottom: 'stone' } },
  [BLOCK_TYPES.CHEST]: { id: 62, name: 'Wooden Chest', solid: true, transparent: false, color: '#866043', sound: 'wood', hardness: 1.5, faces: { top: 'chest_top', side: 'chest_side', bottom: 'oak_planks' } },
  [BLOCK_TYPES.TNT]: { id: 63, name: 'TNT', solid: true, transparent: false, color: '#c9382b', sound: 'grass', hardness: 0.1, faces: { top: 'tnt_top', side: 'tnt_side', bottom: 'tnt_bottom' } },
  [BLOCK_TYPES.SPONGE]: { id: 64, name: 'Sponge', solid: true, transparent: false, color: '#c5c24e', sound: 'grass', hardness: 0.6, faces: { all: 'sponge' } },
  [BLOCK_TYPES.SLIME_BLOCK]: { id: 65, name: 'Slime Block', solid: true, transparent: true, opacity: 0.8, color: '#68b855', sound: 'grass', hardness: 0.2, faces: { all: 'slime' } },
  [BLOCK_TYPES.HONEYCOMB_BLOCK]: { id: 66, name: 'Honeycomb Block', solid: true, transparent: false, color: '#e58e1c', sound: 'grass', hardness: 0.6, faces: { all: 'honeycomb' } },
  [BLOCK_TYPES.HAY_BALE]: { id: 67, name: 'Hay Bale', solid: true, transparent: false, color: '#9e8921', sound: 'grass', hardness: 0.5, faces: { top: 'hay_top', side: 'hay_side', bottom: 'hay_top' } },

  // Nature, Plants & Food
  [BLOCK_TYPES.PUMPKIN]: { id: 68, name: 'Carved Pumpkin', solid: true, transparent: false, color: '#d06a14', sound: 'wood', hardness: 1.0, faces: { top: 'pumpkin_top', side: 'pumpkin_side', bottom: 'pumpkin_top' } },
  [BLOCK_TYPES.JACK_O_LANTERN]: { id: 69, name: "Jack o'Lantern", solid: true, transparent: false, emissive: '#ffaa22', color: '#e87b1c', sound: 'wood', hardness: 1.0, faces: { top: 'pumpkin_top', side: 'jack_side', bottom: 'pumpkin_top' } },
  [BLOCK_TYPES.MELON]: { id: 70, name: 'Melon Block', solid: true, transparent: false, color: '#779922', sound: 'wood', hardness: 1.0, faces: { top: 'melon_top', side: 'melon_side', bottom: 'melon_top' } },
  [BLOCK_TYPES.CACTUS]: { id: 71, name: 'Cactus', solid: true, transparent: false, color: '#4f7d23', sound: 'wood', hardness: 0.5, faces: { top: 'cactus_top', side: 'cactus_side', bottom: 'cactus_bottom' } },
  [BLOCK_TYPES.RED_MUSHROOM_BLOCK]: { id: 72, name: 'Huge Red Mushroom', solid: true, transparent: false, color: '#b82725', sound: 'wood', hardness: 0.4, faces: { all: 'mushroom_red' } },

  // Colorful Wool / Concrete Blocks
  [BLOCK_TYPES.WOOL_WHITE]: { id: 73, name: 'White Wool', solid: true, transparent: false, color: '#e4e4e4', sound: 'grass', hardness: 0.8, faces: { all: 'wool_white' } },
  [BLOCK_TYPES.WOOL_RED]: { id: 74, name: 'Red Wool', solid: true, transparent: false, color: '#9e2b27', sound: 'grass', hardness: 0.8, faces: { all: 'wool_red' } },
  [BLOCK_TYPES.WOOL_BLUE]: { id: 75, name: 'Blue Wool', solid: true, transparent: false, color: '#2e388d', sound: 'grass', hardness: 0.8, faces: { all: 'wool_blue' } },
  [BLOCK_TYPES.WOOL_GREEN]: { id: 76, name: 'Green Wool', solid: true, transparent: false, color: '#495b24', sound: 'grass', hardness: 0.8, faces: { all: 'wool_green' } },
  [BLOCK_TYPES.WOOL_YELLOW]: { id: 77, name: 'Yellow Wool', solid: true, transparent: false, color: '#e5b228', sound: 'grass', hardness: 0.8, faces: { all: 'wool_yellow' } },
  [BLOCK_TYPES.WOOL_BLACK]: { id: 78, name: 'Black Wool', solid: true, transparent: false, color: '#16161b', sound: 'grass', hardness: 0.8, faces: { all: 'wool_black' } },
  [BLOCK_TYPES.WOOL_ORANGE]: { id: 79, name: 'Orange Wool', solid: true, transparent: false, color: '#e06117', sound: 'grass', hardness: 0.8, faces: { all: 'wool_orange' } },
  [BLOCK_TYPES.WOOL_PURPLE]: { id: 80, name: 'Purple Wool', solid: true, transparent: false, color: '#6f269a', sound: 'grass', hardness: 0.8, faces: { all: 'wool_purple' } },
  [BLOCK_TYPES.WOOL_CYAN]: { id: 81, name: 'Cyan Wool', solid: true, transparent: false, color: '#157788', sound: 'grass', hardness: 0.8, faces: { all: 'wool_cyan' } },
  [BLOCK_TYPES.WOOL_PINK]: { id: 82, name: 'Pink Wool', solid: true, transparent: false, color: '#d5658e', sound: 'grass', hardness: 0.8, faces: { all: 'wool_pink' } },

  // Classic Studio & Neon Blocks
  [BLOCK_TYPES.BASEPLATE]: { id: 83, name: 'Studio Baseplate', category: 'classic', solid: true, transparent: false, color: '#636466', sound: 'stone', hardness: 5.0, faces: { top: 'baseplate_top', side: 'baseplate_side', bottom: 'baseplate_side' } },
  [BLOCK_TYPES.SPAWN_PLATE]: { id: 84, name: 'Studio Spawn Pad', category: 'classic', solid: true, transparent: false, color: '#0d69ac', sound: 'stone', hardness: 5.0, faces: { top: 'spawn_plate_top', side: 'baseplate_side', bottom: 'baseplate_side' } },
  [BLOCK_TYPES.NEON_CYAN]: { id: 85, name: 'Neon Cyan Brick', category: 'classic', solid: true, transparent: false, emissive: '#00ffff', color: '#00ffff', sound: 'glass', hardness: 0.5, faces: { all: 'neon_cyan' } },
  [BLOCK_TYPES.NEON_ORANGE]: { id: 86, name: 'Neon Orange Brick', category: 'classic', solid: true, transparent: false, emissive: '#ff6600', color: '#ff6600', sound: 'glass', hardness: 0.5, faces: { all: 'neon_orange' } },
  [BLOCK_TYPES.NEON_PINK]: { id: 87, name: 'Neon Pink Brick', category: 'classic', solid: true, transparent: false, emissive: '#ff00aa', color: '#ff00aa', sound: 'glass', hardness: 0.5, faces: { all: 'neon_pink' } },
  [BLOCK_TYPES.STUD_BRICK_RED]: { id: 88, name: 'Crimson Studded Brick', category: 'classic', solid: true, transparent: false, color: '#c4281c', sound: 'stone', hardness: 1.5, faces: { top: 'stud_red_top', side: 'stud_red_side', bottom: 'stud_red_side' } },
  [BLOCK_TYPES.STUD_BRICK_BLUE]: { id: 89, name: 'Cobalt Studded Brick', category: 'classic', solid: true, transparent: false, color: '#0d69ac', sound: 'stone', hardness: 1.5, faces: { top: 'stud_blue_top', side: 'stud_blue_side', bottom: 'stud_blue_side' } },
  [BLOCK_TYPES.STUD_BRICK_YELLOW]: { id: 90, name: 'Amber Studded Brick', category: 'classic', solid: true, transparent: false, color: '#f5cd30', sound: 'stone', hardness: 1.5, faces: { top: 'stud_yellow_top', side: 'stud_yellow_side', bottom: 'stud_yellow_side' } },

  // --- 16+ AUTHENTIC FURNITURE PIECES ---
  [BLOCK_TYPES.SOFA_RED]: { id: 91, name: 'Red Plush Sofa', category: 'furniture', solid: true, transparent: false, color: '#b91c1c', sound: 'grass', hardness: 0.8, faces: { top: 'sofa_red_top', front: 'sofa_red_front', side: 'sofa_red_side', bottom: 'oak_planks' } },
  [BLOCK_TYPES.SOFA_BLUE]: { id: 92, name: 'Blue Modern Sofa', category: 'furniture', solid: true, transparent: false, color: '#1d4ed8', sound: 'grass', hardness: 0.8, faces: { top: 'sofa_blue_top', front: 'sofa_blue_front', side: 'sofa_blue_side', bottom: 'oak_planks' } },
  [BLOCK_TYPES.WOOD_TABLE]: { id: 93, name: 'Oak Dining Table', category: 'furniture', solid: true, transparent: false, color: '#926a38', sound: 'wood', hardness: 1.0, faces: { top: 'table_top', side: 'table_side', bottom: 'oak_planks' } },
  [BLOCK_TYPES.CHAIR_WOOD]: { id: 94, name: 'Wooden Chair', category: 'furniture', solid: true, transparent: false, color: '#a17342', sound: 'wood', hardness: 0.9, faces: { top: 'chair_seat', front: 'chair_front', back: 'chair_back', side: 'chair_side', bottom: 'oak_planks' } },
  [BLOCK_TYPES.BED_RED]: { id: 95, name: 'Cozy Red Bed', category: 'furniture', solid: true, transparent: false, color: '#dc2626', sound: 'grass', hardness: 0.6, faces: { top: 'bed_red_top', front: 'bed_front', side: 'bed_red_side', bottom: 'oak_planks' } },
  [BLOCK_TYPES.BED_BLUE]: { id: 96, name: 'Royal Blue Bed', category: 'furniture', solid: true, transparent: false, color: '#2563eb', sound: 'grass', hardness: 0.6, faces: { top: 'bed_blue_top', front: 'bed_front', side: 'bed_blue_side', bottom: 'oak_planks' } },
  [BLOCK_TYPES.LAMP_TABLE]: { id: 97, name: 'Warm Lamp', category: 'furniture', solid: true, transparent: false, emissive: '#fffae0', color: '#fef08a', sound: 'glass', hardness: 0.4, faces: { top: 'lamp_top', side: 'lamp_side', bottom: 'iron' } },
  [BLOCK_TYPES.TELEVISION]: { id: 98, name: 'Flat Screen TV', category: 'furniture', solid: true, transparent: false, emissive: '#0ea5e9', color: '#0f172a', sound: 'glass', hardness: 1.2, faces: { front: 'tv_front', top: 'tv_top', side: 'tv_side', back: 'tv_side', bottom: 'tv_side' } },
  [BLOCK_TYPES.KITCHEN_FRIDGE]: { id: 99, name: 'Kitchen Refrigerator', category: 'furniture', solid: true, transparent: false, color: '#cbd5e1', sound: 'stone', hardness: 1.6, faces: { front: 'fridge_front', side: 'fridge_side', top: 'fridge_side', bottom: 'iron' } },
  [BLOCK_TYPES.KITCHEN_STOVE]: { id: 100, name: 'Cooking Stove', category: 'furniture', solid: true, transparent: false, color: '#334155', sound: 'stone', hardness: 1.8, faces: { top: 'stove_top', front: 'stove_front', side: 'stove_side', bottom: 'iron' } },
  [BLOCK_TYPES.KITCHEN_SINK]: { id: 101, name: 'Sink Basin', category: 'furniture', solid: true, transparent: false, color: '#f8fafc', sound: 'stone', hardness: 1.4, faces: { top: 'sink_top', front: 'sink_front', side: 'sink_front', bottom: 'iron' } },
  [BLOCK_TYPES.TOILET]: { id: 102, name: 'Ceramic Toilet', category: 'furniture', solid: true, transparent: false, color: '#ffffff', sound: 'stone', hardness: 1.2, faces: { top: 'toilet_top', front: 'toilet_front', side: 'toilet_front', bottom: 'iron' } },
  [BLOCK_TYPES.BATH_TUB]: { id: 103, name: 'Porcelain Bathtub', category: 'furniture', solid: true, transparent: false, color: '#f1f5f9', sound: 'stone', hardness: 1.5, faces: { top: 'bathtub_top', side: 'bathtub_side', front: 'bathtub_side', bottom: 'iron' } },
  [BLOCK_TYPES.WALL_CLOCK]: { id: 104, name: 'Analog Clock', category: 'furniture', solid: true, transparent: false, color: '#78350f', sound: 'wood', hardness: 0.8, faces: { front: 'clock_face', side: 'clock_side', top: 'clock_side', bottom: 'clock_side' } },
  [BLOCK_TYPES.HOUSE_PLANT]: { id: 105, name: 'Potted House Plant', category: 'furniture', solid: true, transparent: false, color: '#15803d', sound: 'grass', hardness: 0.5, faces: { top: 'plant_top', side: 'plant_side', front: 'plant_side', bottom: 'dirt' } },
  [BLOCK_TYPES.OFFICE_COMPUTER]: { id: 106, name: 'Workstation PC', category: 'furniture', solid: true, transparent: false, emissive: '#38bdf8', color: '#1e293b', sound: 'glass', hardness: 1.1, faces: { front: 'computer_screen', top: 'computer_top', side: 'computer_side', bottom: 'iron' } }
};

// Map string name to block id for Gemini AI generator
export function getBlockIdByName(name) {
  if (!name) return BLOCK_TYPES.STONE;
  const key = String(name).toUpperCase().trim().replace(/[\s-]+/g, '_');
  if (BLOCK_TYPES[key] !== undefined) {
    return BLOCK_TYPES[key];
  }

  const aliases = {
    'WOOD': BLOCK_TYPES.OAK_WOOD,
    'LOG': BLOCK_TYPES.OAK_WOOD,
    'PLANKS': BLOCK_TYPES.OAK_PLANKS,
    'LEAF': BLOCK_TYPES.OAK_LEAVES,
    'LEAVES': BLOCK_TYPES.OAK_LEAVES,
    'BRICK': BLOCK_TYPES.BRICKS,
    'TILES': BLOCK_TYPES.ROOF_TILE,
    'ROOF': BLOCK_TYPES.ROOF_TILE,
    'LANTERN': BLOCK_TYPES.GLOWSTONE,
    'LIGHT': BLOCK_TYPES.GLOWSTONE,
    'TORCH': BLOCK_TYPES.GLOWSTONE,
    'GOLD': BLOCK_TYPES.GOLD_BLOCK,
    'DIAMOND': BLOCK_TYPES.DIAMOND_BLOCK,
    'IRON': BLOCK_TYPES.IRON_BLOCK,
    'STONE_BRICK': BLOCK_TYPES.BRICKS,
    'QUARTZ': BLOCK_TYPES.MARBLE,
    'WHITE_STONE': BLOCK_TYPES.MARBLE,
    'PURPLE': BLOCK_TYPES.OBSIDIAN,
    'PORTAL': BLOCK_TYPES.OBSIDIAN,
    'WINDOW': BLOCK_TYPES.GLASS,
    'SEA_LIGHT': BLOCK_TYPES.SEA_LANTERN,
    'RED_WOOL': BLOCK_TYPES.WOOL_RED,
    'BLUE_WOOL': BLOCK_TYPES.WOOL_BLUE,
    'WHITE_WOOL': BLOCK_TYPES.WOOL_WHITE,
    'BLACK_WOOL': BLOCK_TYPES.WOOL_BLACK,
    'YELLOW_WOOL': BLOCK_TYPES.WOOL_YELLOW,
    'GREEN_WOOL': BLOCK_TYPES.WOOL_GREEN,
    'PURPLE_WOOL': BLOCK_TYPES.WOOL_PURPLE,
    'CYAN_WOOL': BLOCK_TYPES.WOOL_CYAN,
    'PINK_WOOL': BLOCK_TYPES.WOOL_PINK,
    'CHEST': BLOCK_TYPES.CHEST,
    'BOX': BLOCK_TYPES.CHEST,
    'CRAFTING': BLOCK_TYPES.CRAFTING_TABLE,
    'WORKBENCH': BLOCK_TYPES.CRAFTING_TABLE,
    'OVEN': BLOCK_TYPES.FURNACE,
    'FORGE': BLOCK_TYPES.FURNACE,
    'BOOM': BLOCK_TYPES.TNT,
    'EXPLOSIVE': BLOCK_TYPES.TNT,
    'MELON_BLOCK': BLOCK_TYPES.MELON,
    'PUMPKIN_BLOCK': BLOCK_TYPES.PUMPKIN,
    'NETHER': BLOCK_TYPES.NETHERRACK,
    'DARK_STONE': BLOCK_TYPES.BLACKSTONE,
    'CRYSTAL': BLOCK_TYPES.AMETHYST_BLOCK,
    'SLIME': BLOCK_TYPES.SLIME_BLOCK,
    'HONEY': BLOCK_TYPES.HONEYCOMB_BLOCK,
    'HAY': BLOCK_TYPES.HAY_BALE,
    'WHEAT': BLOCK_TYPES.HAY_BALE,
    'PRISMARINE_BRICK': BLOCK_TYPES.PRISMARINE,
    'CHERRY': BLOCK_TYPES.CHERRY_WOOD,
    'CHERRY_BLOSSOM': BLOCK_TYPES.CHERRY_LEAVES,
    'SAKURA': BLOCK_TYPES.CHERRY_LEAVES,
    'BASEPLATE': BLOCK_TYPES.BASEPLATE,
    'SPAWN': BLOCK_TYPES.SPAWN_PLATE,
    'NEON': BLOCK_TYPES.NEON_CYAN,
    'STUDIO': BLOCK_TYPES.BASEPLATE,
    'STUDDED': BLOCK_TYPES.STUD_BRICK_RED,
    'STUD': BLOCK_TYPES.STUD_BRICK_RED,

    // Furniture Aliases
    'SOFA': BLOCK_TYPES.SOFA_RED,
    'COUCH': BLOCK_TYPES.SOFA_RED,
    'RED_SOFA': BLOCK_TYPES.SOFA_RED,
    'BLUE_SOFA': BLOCK_TYPES.SOFA_BLUE,
    'TABLE': BLOCK_TYPES.WOOD_TABLE,
    'DESK': BLOCK_TYPES.WOOD_TABLE,
    'DINING_TABLE': BLOCK_TYPES.WOOD_TABLE,
    'COFFEE_TABLE': BLOCK_TYPES.WOOD_TABLE,
    'CHAIR': BLOCK_TYPES.CHAIR_WOOD,
    'SEAT': BLOCK_TYPES.CHAIR_WOOD,
    'ARMCHAIR': BLOCK_TYPES.SOFA_RED,
    'BED': BLOCK_TYPES.BED_RED,
    'RED_BED': BLOCK_TYPES.BED_RED,
    'BLUE_BED': BLOCK_TYPES.BED_BLUE,
    'LAMP': BLOCK_TYPES.LAMP_TABLE,
    'DESK_LAMP': BLOCK_TYPES.LAMP_TABLE,
    'LIGHT_STAND': BLOCK_TYPES.LAMP_TABLE,
    'TV': BLOCK_TYPES.TELEVISION,
    'TELEVISION': BLOCK_TYPES.TELEVISION,
    'MONITOR': BLOCK_TYPES.TELEVISION,
    'FLATSCREEN': BLOCK_TYPES.TELEVISION,
    'FRIDGE': BLOCK_TYPES.KITCHEN_FRIDGE,
    'REFRIGERATOR': BLOCK_TYPES.KITCHEN_FRIDGE,
    'STOVE': BLOCK_TYPES.KITCHEN_STOVE,
    'OVEN': BLOCK_TYPES.KITCHEN_STOVE,
    'RANGE': BLOCK_TYPES.KITCHEN_STOVE,
    'SINK': BLOCK_TYPES.KITCHEN_SINK,
    'BASIN': BLOCK_TYPES.KITCHEN_SINK,
    'WASHBASIN': BLOCK_TYPES.KITCHEN_SINK,
    'TOILET': BLOCK_TYPES.TOILET,
    'WC': BLOCK_TYPES.TOILET,
    'BATH': BLOCK_TYPES.BATH_TUB,
    'BATHTUB': BLOCK_TYPES.BATH_TUB,
    'TUB': BLOCK_TYPES.BATH_TUB,
    'CLOCK': BLOCK_TYPES.WALL_CLOCK,
    'WALL_CLOCK': BLOCK_TYPES.WALL_CLOCK,
    'PLANT': BLOCK_TYPES.HOUSE_PLANT,
    'HOUSE_PLANT': BLOCK_TYPES.HOUSE_PLANT,
    'POTTED_PLANT': BLOCK_TYPES.HOUSE_PLANT,
    'FLOWER_POT': BLOCK_TYPES.HOUSE_PLANT,
    'COMPUTER': BLOCK_TYPES.OFFICE_COMPUTER,
    'PC': BLOCK_TYPES.OFFICE_COMPUTER,
    'WORKSTATION': BLOCK_TYPES.OFFICE_COMPUTER,

    // Architectural & Construction Aliases
    'ROOF': BLOCK_TYPES.ROOF_TILE,
    'ROOFS': BLOCK_TYPES.ROOF_TILE,
    'ROOF_TILES': BLOCK_TYPES.ROOF_TILE,
    'SHINGLES': BLOCK_TYPES.ROOF_TILE,
    'PILLAR': BLOCK_TYPES.MARBLE,
    'COLUMN': BLOCK_TYPES.MARBLE,
    'WOOD_PILLAR': BLOCK_TYPES.OAK_WOOD,
    'WOOD_COLUMN': BLOCK_TYPES.OAK_WOOD,
    'LOG': BLOCK_TYPES.OAK_WOOD,
    'LOGS': BLOCK_TYPES.OAK_WOOD,
    'PLANKS': BLOCK_TYPES.OAK_PLANKS,
    'TIMBER': BLOCK_TYPES.OAK_PLANKS,
    'WOOD': BLOCK_TYPES.OAK_WOOD,
    'WALL': BLOCK_TYPES.BRICKS,
    'BRICK_WALL': BLOCK_TYPES.BRICKS,
    'STONE_WALL': BLOCK_TYPES.STONE_BRICKS,
    'FLOOR': BLOCK_TYPES.OAK_PLANKS,
    'FLOORING': BLOCK_TYPES.OAK_PLANKS,
    'WOOD_FLOOR': BLOCK_TYPES.OAK_PLANKS,
    'MARBLE_FLOOR': BLOCK_TYPES.MARBLE,
    'STONE_FLOOR': BLOCK_TYPES.STONE,
    'WINDOW': BLOCK_TYPES.GLASS,
    'WINDOWS': BLOCK_TYPES.GLASS,
    'GLASS_PANE': BLOCK_TYPES.GLASS,
    'PANE': BLOCK_TYPES.GLASS,
    'LIGHT': BLOCK_TYPES.GLOWSTONE,
    'LANTERN': BLOCK_TYPES.GLOWSTONE,
    'CHANDELIER': BLOCK_TYPES.GLOWSTONE,
    'TORCH': BLOCK_TYPES.GLOWSTONE,
    'PATH': BLOCK_TYPES.COBBLESTONE,
    'PATHWAY': BLOCK_TYPES.COBBLESTONE,
    'PAVER': BLOCK_TYPES.COBBLESTONE,
    'GRAVEL': BLOCK_TYPES.COBBLESTONE,
    'FENCE': BLOCK_TYPES.OAK_WOOD,
    'RAILING': BLOCK_TYPES.OAK_WOOD,
    'BALCONY': BLOCK_TYPES.OAK_WOOD,
    'BUSH': BLOCK_TYPES.OAK_LEAVES,
    'HEDGE': BLOCK_TYPES.OAK_LEAVES,
    'FOLIAGE': BLOCK_TYPES.OAK_LEAVES,
    'CARPET': BLOCK_TYPES.WOOL_RED,
    'RUG': BLOCK_TYPES.WOOL_RED,
    'RED_CARPET': BLOCK_TYPES.WOOL_RED,
    'BLUE_CARPET': BLOCK_TYPES.WOOL_BLUE,
    'WHITE_CARPET': BLOCK_TYPES.WOOL_WHITE,
    'COUNTER': BLOCK_TYPES.POLISHED_DIORITE,
    'COUNTERTOP': BLOCK_TYPES.POLISHED_DIORITE
  };
  return aliases[key] || BLOCK_TYPES.STONE;
}
